### PR TITLE
Weather App

### PR DESCRIPTION
**Pull request by saimaAnis21**
In this project we did:
1- User enters the name of city for which he/she wants to view the weather data
2- Fetch the weather data using open weather API
3- Display the fetched data on the page
4- Option to toggle between Fahrenheit/Celsius unit of temperature

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work.  💻 👀 ✨
## However, there are some changes required 👀 🧰 🔨 🔧
- When I try to test the app from a fresh install, I get the following error message:
image
- Please make sure you can clone, `npm install` and test the app on your local environment before requesting a new code review, to make sure the next code reviewer can see your app working on their computer.

***[OPTIONAL]***
- You may deploy your project online, to make it easier to test for the next code reviewers.
- You may add automatic geolocation so users see their current weather on page load.

### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- Good progress :+1: 

To improve :factory_worker: [REQUIRED]:

- [ ] Please, make sure that instruction in your readme file is clear because, even if I create the `.env` file and add `API_KEY= '54c6bcf0d3d2d963d92771c4eeb2136f'` I still got error : `Uncaught Error: Cannot find module './apikey'`. As a result; I was not able to run your APP.
- [ ] I suggest that you use tools like grammarly in order to help you with your readme.
- [ ] Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.
- [ ] Please, use this [file](https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml) as a linter config because it  represents style guidelines that you share with your team - which is a group of all Microverse students.

Nice to have:

- [ ] You may deploy your project online, to make it easier to test for the next code reviewers.

- [ ] You may add automatic geolocation so users see their current weather on page load.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUIRED🛑🛑🛑**

Hello @saimaAnis21 
Great work on this project. However, make a small change to get it approved.\
[REQUIRED]: Fix the failing linter errors

That's it.
Happy coding💻💻💻

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- User can search for a specific location :+1: 

To improve :factory_worker: [REQUIRED]:

- [ ] I got error when I enter a location that doesn't exist. Please, make sure that your APP has `error handling` for async/await ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/error_handling_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))


- [ ]  I suggest that you use tools like `grammarly` in order to help you with your readme.

Nice to have:

- [ ]  it has a ‘`loading`’ component that displays from the time the form is submitted until the information comes back from the API ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/loading_component_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Comment by saimaAnis21** [comment]
Can you kindly guide me why I need to use grammarly for the readme. Which part of the readme is incorrect grammatically?
Thank you!!

**Comment by rindrajosia** [comment]
For instance, you have: Run npm install on the terminal to install **`dependancies`** instead of : Run npm install on the terminal to install **`dependencies`**

**Comment by saimaAnis21** [comment]
> Changes Required :red_circle:
> To Highlight: :angel:
> 
> - User can search for a specific location :+1: 
> 
> To improve :factory_worker: [REQUIRED]:
> 
> - [ ] I got error when I enter a location that doesn't exist. Please, make sure that your APP has `error handling` for async/await ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/error_handling_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))
> 
> 
> - [ ]  I suggest that you use tools like `grammarly` in order to help you with your readme.
> 
> Nice to have:
> 
> - [ ]  it has a ‘`loading`’ component that displays from the time the form is submitted until the information comes back from the API ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/loading_component_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
> 
> That's it, you can submit another code review request after making these changes :recycle: :innocent:
> With all my respect :pray:
> Rindra Josia

Can you please tell me what exactly is wrong with my readme. Thank you!!

**Comment by rindrajosia** [comment]
> > Changes Required 🔴
> > To Highlight: 👼
> > 
> > * User can search for a specific location 👍
> > 
> > To improve 🧑‍🏭 [REQUIRED]:
> > 
> > * [ ]  I got error when I enter a location that doesn't exist. Please, make sure that your APP has `error handling` for async/await ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/error_handling_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))
> >   
> > * [ ]   I suggest that you use tools like `grammarly` in order to help you with your readme.
> > 
> > Nice to have:
> > 
> > * [ ]   it has a ‘`loading`’ component that displays from the time the form is submitted until the information comes back from the API ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/loading_component_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
> > 
> > That's it, you can submit another code review request after making these changes ♻️ 😇
> > With all my respect 🙏
> > Rindra Josia
> 
> Can you please tell me what exactly is wrong with my readme. Thank you!!

In fact your readme is good except that, there are minor grammatical errors. Like I said before, you have DEPENDANCIES instead of DEPENDENCIES.

**Review by oloomoses — APPROVED** [review]
# Congratulations, Project Approved. :muscle: :tada: :clap: 
**Hello @saimaAnis21, 
Great job working on the suggested changes from the previous reviews.
You have passed all the requirements for this project :muscle:**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

**Pull request merged**
